language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t damianpm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true damianpm/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'docker-react'
  env: 'DockerReact-env-1'
  bucket_name: 'elasticbeanstalk-eu-west-3-653043762694'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
